name: NASA Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/NASA
    strategy:
      matrix:
        node-version: [14.x, 16.x, 20.x]
        mongodb-version: ['16.0.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-db: ${{ matrix.mongodb-version }}
      - name: Do Something with env files
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          echo $CLIENT_ID
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
